const types = {
    GET_LOGIN: 'GET_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',

    REGISTER: 'REGISTER',

    GET_PROFILE: 'GET_PROFILE',
    EDIT_PROFILE: 'EDIT_PROFILE',
    PROFILE_SUCCESS: 'PROFILE_SUCCESS',
    PROFILE_FAILURE: 'PROFILE_FAILURE',

    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    CHANGE_PASSWORD_COMPLETE: 'CHANGE_PASSWORD_COMPLETE',



    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',

    SUBMIT_SUPPORT: 'SUBMIT_SUPPORT',

    ADD_STORY: 'ADD_STORY',
    ADD_STORY_FAILED: 'ADD_STORY_FAILED',
    ADD_TO_STORY: 'ADD_TO_STORY',


    GET_STORIES: 'GET_STORIES',
    GET_STORIES_SUCCESS: 'GET_STORIES_SUCCESS',
    GET_STORIES_FAILURE: 'GET_STORIES_FAILURE',

    GET_STORY_DETAILS: 'GET_STORY_DETAILS',

    GET_MY_STORIES: 'GET_MY_STORIES',
    GET_MY_STORIES_SUCCESS: 'GET_MY_STORIES_SUCCESS',

    TOGGLE_FAV: 'TOGGLE_FAV'

    // GET_MEALS: 'GET_MEALS',
    // MEALS_SUCCESS: 'MEALS_SUCCESS',
    // MEALS_FAILURE: 'MEALS_FAILURE',
    // CATEGORIES_SUCCESS: 'CATEGORIES_SUCCESS',

    // GET_MY_MEALS: 'GET_MY_MEALS',
    // MY_MEALS_SUCCESS: 'MY_MEALS_SUCCESS',
    // MY_MEALS_FAILURE: 'MY_MEALS_FAILURE',

    // GET_INGREDIENTS: 'GET_INGREDIENTS',
    // INGREDIENTS_SUCCESS: 'INGREDIENTS_SUCCESS',
    // INGREDIENTS_FAILURE: 'INGREDIENTS_FAILURE',
    // ADD_INGREDIENT: 'ADD_INGREDIENT',
    // REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',

    // GET_IMAGES: 'GET_IMAGES'
}

export default types